### ISSUE TITLE
[Bug] java.net.BindException thrown when EventMesh starts.

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#4081]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

There is an exception thrown when EventMesh starts. (When I modify `eventMesh.server.tcp.port=10000` back to `eventMesh.server.tcp.port=10002`, the exception will disappear .)

### How to reproduce

Run EventMesh with the newest master branch.

### Debug logs

2023-06-07 22:28:36,271 ERROR [eventMesh-tcp-server] EventMeshTCPServer(EventMeshTCPServer.java:192) - EventMeshTCPServer RemotingServer Start Err!
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_171]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_171]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_171]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_171]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.79.Final.jar:4.1.79.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
2023-06-07 22:28:36,287 DEBUG [grpc-nio-boss-ELG-1-1] DefaultChannelId(DefaultChannelId.java:101) - -Dio.netty.machineId: 00:50:56:ff:fe:c0:00:08 (auto-detected)
2023-06-07 22:28:36,287 INFO  [eventMesh-tcp-server] EventMeshTCPServer(EventMeshTCPServer.java:270) - shutdown bossGroup, no client is allowed to connect access server
2023-06-07 22:28:36,287 INFO  [eventMesh-tcp-server] ClientSessionGroupMapping(ClientSessionGroupMapping.java:411) - begin to close sessions gracefully

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by pandaapo** [comment]
CC @Alonexc

**Comment by xwm1992** [comment]
Your local tcp server port is occupied by a process, just modify the configuration is ok.

**Comment by pandaapo** [comment]
I will check the port usage of my computer. Because this exception seems to appear stable even after I shut down and restarted.

**Comment by pandaapo** [comment]
Indeed, other application(Baidu Netdisk) is using `10000` port.
