### ISSUE TITLE
[Bug] Startup failed due to NullPointerException.

### ISSUE THREAD

**Issue by Alonexc** [apache/eventmesh#4245]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Windows

### EventMesh version

master

### What happened

eventmesh failed to start.

### How to reproduce
start eventmesh.

```
java.lang.NullPointerException: null
	at org.apache.eventmesh.runtime.core.protocol.http.processor.HandlerService.register(HandlerService.java:107) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.core.protocol.http.processor.HandlerService.register(HandlerService.java:91) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshHTTPServer.registerHTTPRequestProcessor(EventMeshHTTPServer.java:370) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshHTTPServer.init(EventMeshHTTPServer.java:241) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshHTTPServer.start(EventMeshHTTPServer.java:250) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshHttpBootstrap.start(EventMeshHttpBootstrap.java:53) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshServer.start(EventMeshServer.java:165) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:40) [eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.starter.StartUp.main(StartUp.java:25) [main/:?]
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdidde** [comment]
Seems like this issue still occurs with version 1.10.0 and 1.11.0 during docker start

java.lang.NullPointerException: traceServiceType: standalone is not supported
at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_342]
at org.apache.eventmesh.trace.api.TracePluginFactory.getEventMeshTraceService(TracePluginFactory.java:43) ~[eventmesh-trace-api-1.10.0-release.jar:1.10.0-release]
at org.apache.eventmesh.runtime.trace.Trace.traceBuilder(Trace.java:55) ~[eventmesh-runtime-1.10.0-release.jar:1.10.0-release]
at org.apache.eventmesh.runtime.trace.Trace.lambda$getInstance$0(Trace.java:49) ~[eventmesh-runtime-1.10.0-release.jar:1.10.0-release]
at java.util.HashMap.computeIfAbsent(HashMap.java:1128) ~[?:1.8.0_342]
at org.apache.eventmesh.runtime.trace.Trace.getInstance(Trace.java:49) ~[eventmesh-runtime-1.10.0-release.jar:1.10.0-release]
at org.apache.eventmesh.runtime.boot.EventMeshServer.(EventMeshServer.java:105) ~[eventmesh-runtime-1.10.0-release.jar:1.10.0-release]
at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:37) [eventmesh-runtime-1.10.0-release.jar:1.10.0-release]
