### ISSUE TITLE
AbrstractHTTPServer.HTTPHandler.channelRead0 err java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by brampurnot** [apache/eventmesh#4579]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

Hi all! I deployed a standalone event mesh instance on Kubernetes using the docker file provided in the documentation. The workload gets deployed and seems to be stable. I see the logs too and all looks good. 
 
At the same time I deployed the event mesh dashboard and I'm trying to hook both things up now. I also tried using the REST API but I keep on getting this error:
`3-11-24 14:01:39,278 INFO  [pool-16-thread-1] ConsumerManager(ConsumerManager.java:79) - clientInfo check start.....
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:108) - ===========================================SERVER METRICS==================================================
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:110) - {"maxHTTPTPS":"0.0","avgHTTPTPS":"0.0","maxHTTPCOST":"0","avgHTTPCOST":"0.0","avgHTTPBodyDecodeCost":"0.0", "httpDiscard":"0"}
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:119) - {"maxBatchSendMsgTPS":"0.0","avgBatchSendMsgTPS":"0.0", "sum":"0", "sumFail":"0", "sumFailRate":"0.00", "discard":"0"}
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:129) - {"maxSendMsgTPS":"0.0","avgSendMsgTPS":"0.0", "sum":"0", "sumFail":"0", "sumFailRate":"0.00", "replyMsg":"0", "replyFail":"0"}
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:140) - {"maxPushMsgTPS":"0.0","avgPushMsgTPS":"0.0", "sum":"0", "sumFail":"0", "sumFailRate":"0.0", "maxClientLatency":"0.0", "avgClientLatency":"0.0"}
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:151) - {"batchMsgQ":"0","sendMsgQ":"0","pushMsgQ":"0","httpRetryQ":"0"}
2023-11-24 14:01:40,278 INFO  [eventMesh-metrics-2] httpMonitor(HTTPMetricsServer.java:157) - {"batchAvgSend2MQCost":"0.0", "avgSend2MQCost":"0.0", "avgReply2MQCost":"0.0"}
2023-11-24 14:01:49,084 INFO  [pool-6-thread-1] ConsumerManager(ConsumerManager.java:199) - grpc client info check
2023-11-24 14:01:49,084 DEBUG [pool-6-thread-1] ConsumerManager(ConsumerManager.java:205) - total number of ConsumerGroupClients: 0
2023-11-24 14:01:49,278 INFO  [pool-16-thread-1] ConsumerManager(ConsumerManager.java:79) - clientInfo check start.....
2023-11-24 14:01:59,071 INFO  [pool-6-thread-1] ConsumerManager(ConsumerManager.java:199) - grpc client info check
2023-11-24 14:01:59,071 DEBUG [pool-6-thread-1] ConsumerManager(ConsumerManager.java:205) - total number of ConsumerGroupClients: 0
2023-11-24 14:01:59,278 INFO  [pool-16-thread-1] ConsumerManager(ConsumerManager.java:79) - clientInfo check start.....
2023-11-24 14:02:04,562 ERROR [eventMesh-http-worker-7] EventMeshHTTPServer(AbstractHTTPServer.java:385) - AbrstractHTTPServer.HTTPHandler.channelRead0 err
java.lang.NullPointerException: null
        at org.apache.eventmesh.runtime.boot.AbstractHTTPServer$HTTPHandler.channelRead0(AbstractHTTPServer.java:364) [eventmesh-runtime-1.4.0-release.jar:1.4.0-release]
        at org.apache.eventmesh.runtime.boot.AbstractHTTPServer$HTTPHandler.channelRead0(AbstractHTTPServer.java:300) [eventmesh-runtime-1.4.0-release.jar:1.4.0-release]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]`

Has anyone faced this before or any idea what it could be? 

Any help is appreciated!
Bram

**Comment by brampurnot** [comment]
Thanks! I will give that a try

**Comment by brampurnot** [comment]
So I created a new image myself but I'm getting this error when I try to start the container locally:
`2023-11-27 13:58:34,165 main DEBUG org.apache.logging.log4j.core.util.SystemClock does not support precise timestamps.
2023-11-27 13:58:34,168 main DEBUG Reconfiguration complete for context[name=63947c6b] at URI /data/app/eventmesh/conf/log4j2.xml (org.apache.logging.log4j.core.LoggerContext@b9b00e0) with optional ClassLoader: null
2023-11-27 13:58:34,170 main DEBUG Shutdown hook enabled. Registering a new one.
2023-11-27 13:58:34,174 main DEBUG LoggerContext[name=63947c6b, org.apache.logging.log4j.core.LoggerContext@b9b00e0] started OK.
2023-11-27 13:58:34,531 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.acl.AclService, extensionClass: class org.apache.eventmesh.acl.impl.AclServiceImpl
2023-11-27 13:58:34,546 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.acl.AclService, extensionClass: class org.apache.eventmesh.auth.token.impl.AuthTokenServiceImpl
2023-11-27 13:58:34,548 INFO  [main] EventMeshExtensionFactory(EventMeshExtensionFactory.java:103) - initialize extension instance success, extensionClass: interface org.apache.eventmesh.api.acl.AclService, extensionInstanceName: security
2023-11-27 13:58:34,576 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.meta.MetaService, extensionClass: class org.apache.eventmesh.meta.consul.service.ConsulMetaService
2023-11-27 13:58:34,582 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.meta.MetaService, extensionClass: class org.apache.eventmesh.meta.etcd.service.EtcdMetaService
2023-11-27 13:58:34,592 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.meta.MetaService, extensionClass: class org.apache.eventmesh.meta.nacos.service.NacosMetaService
2023-11-27 13:58:34,601 INFO  [main] JarExtensionClassLoader(JarExtensionClassLoader.java:131) - load extension class success, extensionType: interface org.apache.eventmesh.api.meta.MetaService, extensionClass: class org.apache.eventmesh.meta.zookeeper.service.ZookeeperMetaService
2023-11-27 13:58:34,607 WARN  [main] EventMeshExtensionFactory(EventMeshExtensionFactory.java:96) - Get extension instance class org.apache.eventmesh.api.meta.MetaService is null
2023-11-27 13:58:34,609 ERROR [main] MetaStorage(MetaStorage.java:61) - can't load the metaService plugin, please check.
2023-11-27 13:58:34,610 ERROR [main] EventMeshStartup(EventMeshStartup.java:55) - EventMesh start fail.
java.lang.RuntimeException: can't load the metaService plugin, please check.
	at org.apache.eventmesh.runtime.meta.MetaStorage.metaStorageBuilder(MetaStorage.java:62) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1126) ~[?:1.8.0_111]
	at org.apache.eventmesh.runtime.meta.MetaStorage.getInstance(MetaStorage.java:54) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshServer.<init>(EventMeshServer.java:77) ~[eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.runtime.boot.EventMeshStartup.main(EventMeshStartup.java:38) [eventmesh-runtime-1.9.0-release.jar:1.9.0-release]
2023-11-27 13:58:34,655 pool-1-thread-1 DEBUG Stopping LoggerContext[name=63947c6b, org.apache.logging.log4j.core.LoggerContext@b9b00e0]
2023-11-27 13:58:34,657 pool-1-thread-1 DEBUG Stopping LoggerContext[name=63947c6b, org.apache.logging.log4j.core.LoggerContext@b9b00e0]...
2023-11-27 13:58:34,670 pool-1-thread-1 DEBUG Shutting down OutputStreamManager SYSTEM_OUT.false.false
2023-11-27 13:58:34,671 pool-1-thread-1 DEBUG OutputStream closed
2023-11-27 13:58:34,672 pool-1-thread-1 DEBUG Shut down OutputStreamManager SYSTEM_OUT.false.false, all resources released: true
2023-11-27 13:58:34,672 pool-1-thread-1 DEBUG Appender console stopped with status true
2023-11-27 13:58:34,673 pool-1-thread-1 DEBUG Log4j2 ConfigurationScheduler shutting down threads in java.util.concurrent.ScheduledThreadPoolExecutor@44ba6c81[Running, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 0]
2023-11-27 13:58:34,675 pool-1-thread-1 DEBUG Stopped XmlConfiguration[location=/data/app/eventmesh/conf/log4j2.xml] OK
2023-11-27 13:58:34,676 pool-1-thread-1 DEBUG Stopped LoggerContext[name=63947c6b, org.apache.logging.log4j.core.LoggerContext@b9b00e0] with status true`

Anyone saw this before?

Bram

**Comment by brampurnot** [comment]
Building it ourselves worked! Thanks.
