### ISSUE TITLE
[Doc] The introductions of EventMesh Connector and EventMesh Storage are incorrect

### ISSUE THREAD

**Issue by pandaapo** [apache/eventmesh#4682]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

https://github.com/apache/eventmesh-site/issues/159

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by VishalMCF** [comment]
@pandaapo  @Pil0tXia @yanrongzhen 

我尝试了两件事
1. 存储类型为 RocketMQ：- 这里我收到与未找到代理相关的异常。 它来自 RocketMQ 内部 Java 库。 我正在使用 docker-compose.yml 文件运行 RocketMQ Namesrv、RocketMQ Broker 和 RocketMQ 控制台。 我能够成功生成容器。 我还能够从控制台 UI 创建主题并发送消息。 奇怪的是，尽管有我的 RocketMQ 运行的确切域，但它说找不到代理。
2. 存储类型：- Kafka 或独立。
此处 AsyncPublishInstance 能够成功发布消息。 但是在打开消费者实例后，它抛出了这个错误：-
`引起原因：org.apache.eventmesh.common.exception.EventMeshException：errorCode：7，errorMessage：eventMesh协议[body]错误未经授权的webhook URL：http://[fe80:0:0:0:ce81:b1c:bd2c :69e%utun2]:8088/子/测试`


我需要为此做一些额外的配置吗？ 请提出您的任何想法。
如果我可以成功运行该示例，那么我可以处理上述问题并以 Kafka 作为存储层示例对文档进行更改。


I tried two things 
1. Storage type as RocketMQ:- Here I was getting an exception related to broker not found. It was coming from rocketmq internal java libraries. I was running rocketmq namesrv, rocketmq broker, and rocketmq console using a docker-compose.yml file. I was able to successfully spawn the containers. I was also able to create topics from the console UI and send messages. Strange thing is that it was saying broker not found despite having the exact domain on which my rocketmq was running.
2. Storage Type :- Kafka or Standalone.
Here the AsyncPublishInstance was able to successfully publish the message. But after switching on the consumer instance it was throwing this error:-
`Caused by: org.apache.eventmesh.common.exception.EventMeshException: errorCode: 7, errorMessage: eventMesh protocol[body] error unauthorized webhook URL: http://[fe80:0:0:0:ce81:b1c:bd2c:69e%utun2]:8088/sub/test`


Do I have to do some additional configuration for this? Please suggest any ideas you have.
If I can successfully run the example then I can take up the above issue and make changes in the doc with Kafka as storage layer example.

**Comment by VishalMCF** [comment]
@pandaapo @Pil0tXia 
I confirm that adding that VM parameter in the example configuration of consumer worked. Thanks a lot for that.

And as you asked here is the stacktrace of the exception which I was getting while using rocketmq as a broker.

`org.apache.eventmesh.api.exception.StorageRuntimeException: Send message to RocketMQ broker failed.
	at org.apache.eventmesh.storage.rocketmq.producer.AbstractProducer.checkProducerException(AbstractProducer.java:136) ~[eventmesh-storage-rocketmq-1.9.0-release.jar:1.9.0-release]
	at org.apache.eventmesh.storage.rocketmq.producer.ProducerImpl$2.onException(ProducerImpl.java:198) [eventmesh-storage-rocketmq-1.9.0-release.jar:1.9.0-release]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.onExceptionImpl(MQClientAPIImpl.java:644) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:604) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.onExceptionImpl(MQClientAPIImpl.java:634) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:604) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.onExceptionImpl(MQClientAPIImpl.java:634) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:604) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:497) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:819) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:576) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.access$300(DefaultMQProducerImpl.java:98) [rocketmq-client-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl$3.run(DefaultMQProducerImpl.java:503) [rocketmq-client-4.9.5.jar:4.9.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_392]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_392]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_392]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_392]
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: **connect to 172.30.0.4:10911** failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeAsync(NettyRemotingClient.java:548) ~[rocketmq-remoting-4.9.5.jar:4.9.5]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageAsync(MQClientAPIImpl.java:542) ~[rocketmq-client-4.9.5.jar:4.9.5]
	... 14 more`

**Comment by VishalMCF** [comment]
由于我对使用 kafka 存储启动 eventmesh 有正确的理解，我可以承担编辑文档的任务吗？
@pandaapo As I have a proper understanding of launching the eventmesh with kafka storage can I take up this task of diting the documentation?
