### ISSUE TITLE
[Bug] Empty class member cause NullpointerException

### ISSUE THREAD

**Issue by scwlkq** [apache/eventmesh#4770]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Environment

Mac

### EventMesh version

master

### What happened

Runtime（Storage：Local Rocketmq ） + Http Source Connector

![image](https://github.com/apache/eventmesh/assets/89067331/604219b6-f239-413a-8ef2-44adfd613b4f)
请求的路径应该是：curl发送请求->CloudEvent->ConnectRecord-> runtime(storage)
然后我发现是在CloudEvent->ConnectRecord转化的过程中position属性为null：
![image](https://github.com/apache/eventmesh/assets/89067331/ea986798-dd2b-460f-993a-b10228e11144)

但是关于消息写入的offset和partition这些属性 应该是由storage的相关模块写入，但是我在CloudEventUtil里看到了关于这个的todo？

### How to reproduce

run Runtime（Storage：Local Rocketmq ） + Http Source Connector

### Debug logs

```Java
2024-02-16 00:11:21,099 DEBUG [vert.x-eventloop-thread-0] ZlibCodecFactory(ZlibCodecFactory.java:39) - -Dio.netty.noJdkZlibDecoder: false
2024-02-16 00:11:21,099 DEBUG [vert.x-eventloop-thread-0] ZlibCodecFactory(ZlibCodecFactory.java:42) - -Dio.netty.noJdkZlibEncoder: false
2024-02-16 00:11:21,170 INFO  [vert.x-eventloop-thread-0] HttpSourceConnector(HttpSourceConnector.java:100) - [HttpSourceConnector] Succeed to convert payload into CloudEvent. StatusCode=200
2024-02-16 00:11:21,174 INFO  [pool-3-thread-1] CloudEventUtil(CloudEventUtil.java:69) - handle receive events testdata



Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at org.apache.eventmesh.openconnect.offsetmgmt.api.storage.OffsetStorageWriterImpl.writeOffset(OffsetStorageWriterImpl.java:57)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at java.util.Collections$UnmodifiableMap.forEach(Collections.java:1507)
	at org.apache.eventmesh.openconnect.SourceWorker.commitOffsets(SourceWorker.java:346)
	at org.apache.eventmesh.openconnect.SourceWorker.startPollAndSend(SourceWorker.java:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by xwm1992** [comment]
可以修复一下这个bug，对于http source connector不需要对应的offset，可以对空指针做一个兼容
