### ISSUE TITLE
关于类型转换问题

### ISSUE THREAD

**Issue by 9997766** [apache/eventmesh#4801]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

我用docker运行eventmesh 服务端，用rocketmq作为存储，用sdk中的http作为subsciber消费消息时，eventmesh.out的日志报如下错误，我猜测是因为不同的类加载器，导致的EventMeshConsumeConcurrentlyContext 和ConsumeConcurrentlyContext 不认，应该把plugin下的rocket-storage的包，拷贝到apps下能解决问题，
是否能重新打镜像包，放到库上？

tenerConcurrently.java:63) - handleMessage fail
java.lang.ClassCastException: org.apache.rocketmq.client.consumer.listener.ConsumeConcurrentlyContext cannot be cast to org.apache.eventmesh.storage.rocketmq.patch.EventMeshConsumeConcurrentlyContext
        at org.apache.eventmesh.storage.rocketmq.patch.EventMeshMessageListenerConcurrently.consumeMessage(EventMeshMessageListenerConcurrently.java:44) [eventmesh-storage-rocketmq-1.10.0-release.jar:1.10.0-release]
        at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:402) [rocketmq-client-4.9.5.jar:4.9.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]  如何处理

**Comment by xwm1992** [comment]
Okay, we will test this issue again and will provide feedback later.

**Comment by Pil0tXia** [comment]
>应该把plugin下的rocket-storage的包，拷贝到apps下能解决问题

I think this is not a good way to solve this issue, since the jar files under `/apps` are all APIs like `eventmesh-storage-api-1.10.0-release.jar` and shouldn't have a specific implementation.

Will you reproduce this issue with source code? It seems the exception was throwed at `org.apache.eventmesh.storage.rocketmq.patch.EventMeshMessageListenerConcurrently` Line 44.

**Comment by yinglalanice** [comment]
这个问题我也遇到了，使用源码启动的方式没有问题，但是不管是使用二进制还是Docker的启动方式都有问题。

分析了一下原因可能是org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService 这个类在两个包中都存在：**eventmesh-storage-rocketmq-1.10.0-release.jar**和**rocketmq-client-4.9.5.jar**。在本地源码启动时可能类加载的是**eventmesh-storage-rocketmq-1.10.0-release.jar**所以没有问题，二进制部署时类加载**rocketmq-client-4.9.5.jar**，导致创建的类型就是ConsumeConcurrentlyContext而不是EventMeshConsumeConcurrentlyContext。

解决方案就是自定义一个类加载器，先吧**eventmesh-storage-rocketmq-1.10.0-release.jar**包中的ConsumeMessageConcurrentlyService加载进来，但是还没有想好这个类加载器放在哪更优雅一些
